#!/usr/bin/env bash
# Installs the portable buzz-alis Linux build for the current user.
#
# Nothing here needs root: binaries go to ~/.local/share/buzz-alis, a launcher
# to ~/.local/bin/buzz-alis, and a desktop entry (plus the buzz:// scheme
# handler used by Lab deep links) to ~/.local/share/applications.
#
# Re-running the script over an existing install replaces it in place.
set -euo pipefail

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${PREFIX:-$HOME/.local}"
APP_DIR="${BUZZ_ALIS_APP_DIR:-$HOME/.local/share/buzz-alis}"
BIN_DIR="$PREFIX/bin"
DESKTOP_DIR="$PREFIX/share/applications"
ICON_DIR="$PREFIX/share/icons/hicolor/128x128/apps"

BINARIES=(buzz-desktop buzz buzz-acp buzz-agent buzz-backend-kubernetes buzz-dev-mcp git-credential-nostr)

for bin in "${BINARIES[@]}"; do
    if [[ ! -f "$PKG_DIR/$bin" ]]; then
        echo "error: $bin missing from $PKG_DIR — is this package complete?" >&2
        exit 1
    fi
done

echo "==> Installing to $APP_DIR"
mkdir -p "$APP_DIR" "$BIN_DIR" "$DESKTOP_DIR" "$ICON_DIR"
# Remove the old binaries first: overwriting a running executable in place
# fails with ETXTBSY, and a stale sidecar left behind would still be launched.
for bin in "${BINARIES[@]}"; do
    rm -f "$APP_DIR/$bin"
    install -m 755 "$PKG_DIR/$bin" "$APP_DIR/$bin"
done
install -m 644 "$PKG_DIR/BUILD-MANIFEST.txt" "$APP_DIR/BUILD-MANIFEST.txt"
[[ -f "$PKG_DIR/icon.png" ]] && install -m 644 "$PKG_DIR/icon.png" "$ICON_DIR/buzz-alis.png"

echo "==> Writing launcher $BIN_DIR/buzz-alis"
cat > "$BIN_DIR/buzz-alis" <<LAUNCHER
#!/usr/bin/env bash
# Launcher for the portable buzz-alis build. Generated by install.sh.
set -euo pipefail
APP_DIR="$APP_DIR"
LAUNCHER
cat >> "$BIN_DIR/buzz-alis" <<'LAUNCHER'
ARGS=()
for arg in "$@"; do
    case "$arg" in
        # Last resort for a window that will not paint: run through XWayland
        # instead of the Wayland backend. Everything WebKit-rendering related
        # belongs to the app's own --safe-rendering flag, which falls through
        # to buzz-desktop untouched -- do NOT set WEBKIT_* here. In particular
        # WEBKIT_DISABLE_DMABUF_RENDERER=1, the switch every older guide
        # recommends, empties WebKit's buffer transport set on current
        # WebKitGTK and crashes the web process (see
        # desktop/src-tauri/src/webkit_rendering.rs and upstream #3654).
        --x11)
            export GDK_BACKEND=x11
            ;;
        *) ARGS+=("$arg") ;;
    esac
done
exec "$APP_DIR/buzz-desktop" ${ARGS[@]+"${ARGS[@]}"}
LAUNCHER
chmod 755 "$BIN_DIR/buzz-alis"

echo "==> Writing desktop entry $DESKTOP_DIR/buzz-alis.desktop"
cat > "$DESKTOP_DIR/buzz-alis.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=Buzz Alis
Comment=Buzz desktop (buzz-alis fork)
Exec=$BIN_DIR/buzz-alis %U
Icon=buzz-alis
Terminal=false
Categories=Network;Chat;Development;
StartupWMClass=Buzz
MimeType=x-scheme-handler/buzz;
DESKTOP

command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$DESKTOP_DIR" >/dev/null 2>&1 || true
command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -q -t -f "$PREFIX/share/icons/hicolor" >/dev/null 2>&1 || true
# Claim buzz:// so `xdg-open buzz://lab` reaches this build (Lab deep links).
command -v xdg-mime >/dev/null 2>&1 && xdg-mime default buzz-alis.desktop x-scheme-handler/buzz >/dev/null 2>&1 || true

echo
echo "Installed. Run it with:  buzz-alis"
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "NOTE: $BIN_DIR is not on your PATH — add it, or run $BIN_DIR/buzz-alis" ;;
esac
echo "If the window comes up blank:  buzz-alis --safe-rendering   (or --x11)"
echo
bash "$PKG_DIR/check-deps.sh" || true
