import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

const host = process.env.TAURI_DEV_HOST;
const previewAllowedHost = process.env.BUZZ_PREVIEW_ALLOWED_HOST;
const webWorkspaceProfile = process.env.BUZZ_BUILD_WEB_WORKSPACE_PROFILE ?? "";
const indexHtml = readFileSync(
  new URL("./index.html", import.meta.url),
  "utf8",
);
const inlineScriptHashes = [
  ...indexHtml.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g),
]
  .map((match) => match[1])
  .filter((script) => script.length > 0)
  .map(
    (script) =>
      `'sha256-${createHash("sha256").update(script).digest("base64")}'`,
  );
const previewScriptPolicy = ["'self'", ...inlineScriptHashes].join(" ");

// https://vite.dev/config/
export default defineConfig(async () => ({
  // This exact build variable is also consumed by Rust via option_env!. Keep
  // Vite's public env namespace closed and expose only the normalized profile
  // handshake needed by the trusted local renderer.
  define: {
    __BUZZ_BUILD_WEB_WORKSPACE_PROFILE__: JSON.stringify(webWorkspaceProfile),
  },
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
      "@features-manifest": path.resolve(
        import.meta.dirname,
        "../preview-features.json",
      ),
      "@model-capabilities-manifest": path.resolve(
        import.meta.dirname,
        "../scripts/model-capabilities.json",
      ),
    },
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: parseInt(process.env.VITE_PORT || "1420", 10),
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
  preview: {
    allowedHosts: previewAllowedHost ? [previewAllowedHost] : undefined,
    headers: {
      "Cache-Control": "no-store",
      "Content-Security-Policy": `default-src 'self'; script-src ${previewScriptPolicy}; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; media-src 'self' data: blob:; worker-src 'self' blob:; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'`,
      "Cross-Origin-Resource-Policy": "same-origin",
      "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
      "Referrer-Policy": "no-referrer",
      "X-Content-Type-Options": "nosniff",
      "X-Frame-Options": "DENY",
    },
  },
}));
